//! OpenOpus snapshot provider.
//!
//! OpenOpus (<https://openopus.org>) curates a canonical list of classical
//! composers and works. Their public API is rate-limited but stable; we
//! ship a pre-baked snapshot (`src-tauri/data/openopus.json`) embedded
//! via `include_bytes!` so the Hub can serve "Browse composers / Browse
//! by era / Browse by genre" pages instantly, with zero network cost on
//! first launch.
//!
//! The snapshot is regenerated by the script in
//! `docs/classical/scripts/snapshot_openopus.sh` (kept side-by-side with
//! the design doc), wired through MB to resolve canonical MBIDs. See
//! `docs/classical/phase-2-browse.md` for the curation flow.
//!
//! Provider responsibilities:
//!   1. Static lookups: `top_composers`, `composers_by_era`, `lookup_*_by_*`.
//!   2. `enrich_composer` impl: when MB returned a composer with empty
//!      era / dates, fill them from the snapshot. We never overwrite
//!      values MB already provided (MB is canonical for identity).
//!
//! The provider holds no I/O, no rate-limiter, no HTTP client — it's pure
//! lookup. Cache TTLs from §3.3 do not apply: data is bundle-local.
//!
//! Bit-perfect contract: read-only. No audio routing involvement.

use std::collections::HashMap;
use std::sync::OnceLock;

use async_trait::async_trait;
use serde::Deserialize;

use super::super::types::{Composer, ComposerSummary, Era, Genre, Recording, Work};
use super::ClassicalProvider;
use crate::SoneError;

const SNAPSHOT_BYTES: &[u8] = include_bytes!("../../../data/openopus.json");

/// Pre-baked snapshot, parsed once on first access. Kept in a `OnceLock`
/// so the parse cost (~5 ms) is paid once and shared across the process.
static SNAPSHOT: OnceLock<OpenOpusSnapshot> = OnceLock::new();

fn snapshot() -> &'static OpenOpusSnapshot {
    SNAPSHOT.get_or_init(|| {
        serde_json::from_slice::<OpenOpusSnapshot>(SNAPSHOT_BYTES)
            .expect("openopus snapshot is malformed — rebuild it via the snapshot script")
    })
}

// ---------------------------------------------------------------------------
// Wire shapes (match the JSON produced by `snapshot_openopus.sh`)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Deserialize)]
pub struct OpenOpusSnapshot {
    pub schema_version: u32,
    pub generated_at: String,
    pub composers: Vec<OpenOpusComposer>,
    pub works_by_oo_id: HashMap<String, Vec<OpenOpusWork>>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct OpenOpusComposer {
    pub mbid: String,
    pub open_opus_id: String,
    pub name: String,
    pub full_name: Option<String>,
    pub birth_year: Option<i32>,
    pub death_year: Option<i32>,
    /// Raw OpenOpus epoch label, e.g. "Baroque", "Late Romantic".
    pub epoch: Option<String>,
    pub portrait_url: Option<String>,
    pub popular: bool,
}

#[derive(Debug, Clone, Deserialize)]
pub struct OpenOpusWork {
    pub id: String,
    pub title: String,
    pub subtitle: Option<String>,
    /// Raw OpenOpus genre label, e.g. "Orchestral", "Keyboard", "Stage".
    pub genre: Option<String>,
    pub popular: bool,
    pub recommended: bool,
    pub searchterms: Option<String>,
}

// ---------------------------------------------------------------------------
// Provider
// ---------------------------------------------------------------------------

pub struct OpenOpusProvider;

impl OpenOpusProvider {
    pub fn new() -> Self {
        // Force a parse on construction so any malformed bundle fails fast
        // at startup rather than on the first user navigation.
        let _ = snapshot();
        Self
    }

    /// Top-N composers ordered by snapshot order (popular first thanks
    /// to the snapshot-build sort), capped at the snapshot length.
    pub fn top_composers(&self, limit: usize) -> Vec<ComposerSummary> {
        let snap = snapshot();
        let mut out: Vec<ComposerSummary> = snap
            .composers
            .iter()
            .map(composer_to_summary)
            .collect();
        // Stable sort: popular first, then by name.
        out.sort_by(|a, b| {
            b.popular
                .cmp(&a.popular)
                .then_with(|| a.name.to_lowercase().cmp(&b.name.to_lowercase()))
        });
        out.truncate(limit);
        out
    }

    /// All composers in a given era. Useful for `BrowsePeriods` drill-down.
    pub fn composers_by_era(&self, era: Era) -> Vec<ComposerSummary> {
        snapshot()
            .composers
            .iter()
            .filter(|c| era_for_epoch_label(c.epoch.as_deref(), c.birth_year) == era)
            .map(composer_to_summary)
            .collect()
    }

    pub fn lookup_composer_by_mbid(&self, mbid: &str) -> Option<&'static OpenOpusComposer> {
        snapshot().composers.iter().find(|c| c.mbid == mbid)
    }

    pub fn lookup_composer_summary(&self, mbid: &str) -> Option<ComposerSummary> {
        self.lookup_composer_by_mbid(mbid).map(composer_to_summary)
    }

    /// All snapshot works for a composer (by MBID). Returns an empty Vec
    /// when the composer is outside the snapshot.
    pub fn works_for_composer(&self, mbid: &str) -> Vec<&'static OpenOpusWork> {
        let snap = snapshot();
        let oo_id = match snap.composers.iter().find(|c| c.mbid == mbid) {
            Some(c) => &c.open_opus_id,
            None => return Vec::new(),
        };
        snap.works_by_oo_id
            .get(oo_id)
            .map(|v| v.iter().collect())
            .unwrap_or_default()
    }
}

impl Default for OpenOpusProvider {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn composer_to_summary(c: &OpenOpusComposer) -> ComposerSummary {
    ComposerSummary {
        mbid: c.mbid.clone(),
        open_opus_id: Some(c.open_opus_id.clone()),
        name: c.full_name.clone().unwrap_or_else(|| c.name.clone()),
        full_name: c.full_name.clone(),
        birth_year: c.birth_year,
        death_year: c.death_year,
        era: era_for_epoch_label(c.epoch.as_deref(), c.birth_year),
        portrait_url: c.portrait_url.clone(),
        popular: c.popular,
    }
}

/// Map OpenOpus epoch label → our `Era`. Falls back to a year-based bucket
/// for missing labels so we always produce something useful.
pub fn era_for_epoch_label(label: Option<&str>, birth_year: Option<i32>) -> Era {
    if let Some(s) = label {
        let lower = s.trim().to_lowercase();
        let mapped = match lower.as_str() {
            "medieval" => Some(Era::Medieval),
            "renaissance" => Some(Era::Renaissance),
            "baroque" => Some(Era::Baroque),
            "classical" => Some(Era::Classical),
            "early romantic" => Some(Era::EarlyRomantic),
            "romantic" => Some(Era::Romantic),
            "late romantic" => Some(Era::LateRomantic),
            "20th century" | "early 20th c." | "early 20th century" => {
                Some(Era::TwentiethCentury)
            }
            "post-war" | "post war" | "postwar" => Some(Era::PostWar),
            "21st century" | "contemporary" => Some(Era::Contemporary),
            _ => None,
        };
        if let Some(e) = mapped {
            return e;
        }
    }
    match birth_year {
        Some(y) if y < 1400 => Era::Medieval,
        Some(y) if y < 1600 => Era::Renaissance,
        Some(y) if y < 1750 => Era::Baroque,
        Some(y) if y < 1800 => Era::Classical,
        Some(y) if y < 1850 => Era::EarlyRomantic,
        Some(y) if y < 1900 => Era::Romantic,
        Some(y) if y < 1930 => Era::TwentiethCentury,
        Some(y) if y < 1960 => Era::PostWar,
        Some(_) => Era::Contemporary,
        None => Era::Unknown,
    }
}

/// Map an OpenOpus `genre` label to our internal `Genre` enum. The
/// snapshot uses six labels; we expand them to the eleven-bucket model
/// the Hub renders. Returns `None` when the OpenOpus label is missing.
pub fn genre_for_oo_label(label: Option<&str>) -> Option<Genre> {
    let s = label?.trim();
    let lower = s.to_lowercase();
    match lower.as_str() {
        "keyboard" => Some(Genre::SoloInstrumental),
        "orchestral" => Some(Genre::Orchestral),
        "chamber" => Some(Genre::Chamber),
        // OpenOpus collapses opera + ballet under "Stage". We surface
        // them as Opera since most stage works in the snapshot are operas.
        "stage" => Some(Genre::Opera),
        "vocal" => Some(Genre::Vocal),
        "other" => Some(Genre::Other),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Trait impl — best-effort enrichment for `Composer` (Work / Recording
// stay untouched; OpenOpus does not carry MBIDs for either).
// ---------------------------------------------------------------------------

#[async_trait]
impl ClassicalProvider for OpenOpusProvider {
    fn name(&self) -> &'static str {
        "openopus"
    }

    async fn enrich_composer(&self, c: &mut Composer) -> Result<(), SoneError> {
        let entry = match self.lookup_composer_by_mbid(&c.mbid) {
            Some(e) => e,
            None => return Ok(()),
        };
        if c.full_name.is_none() {
            c.full_name = entry.full_name.clone();
        }
        if c.open_opus_id.is_none() {
            c.open_opus_id = Some(entry.open_opus_id.clone());
        }
        if c.portrait_url.is_none() {
            c.portrait_url = entry.portrait_url.clone();
        }
        if matches!(c.era, Era::Unknown) {
            c.era = era_for_epoch_label(entry.epoch.as_deref(), entry.birth_year);
        }
        if c.birth.is_none() {
            if let Some(year) = entry.birth_year {
                c.birth = Some(super::super::types::LifeEvent {
                    year: Some(year),
                    date: None,
                    place: None,
                });
            }
        }
        if c.death.is_none() {
            if let Some(year) = entry.death_year {
                c.death = Some(super::super::types::LifeEvent {
                    year: Some(year),
                    date: None,
                    place: None,
                });
            }
        }
        Ok(())
    }

    async fn enrich_work(&self, _w: &mut Work) -> Result<(), SoneError> {
        Ok(())
    }

    async fn enrich_recording(&self, _r: &mut Recording) -> Result<(), SoneError> {
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Tests (run against a tiny in-memory fixture so the embedded snapshot
// is exercised exactly once via `OpenOpusProvider::new`).
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snapshot_loads_and_has_canon() {
        let provider = OpenOpusProvider::new();
        // Pull the full canon — the snapshot ships ~33 composers, so 50 is
        // a safe cap that always returns the entire bundle.
        let top = provider.top_composers(50);
        assert!(top.len() >= 20, "expected ≥ 20 composers, got {}", top.len());
        let has_beethoven = top
            .iter()
            .any(|c| c.full_name.as_deref().unwrap_or("") == "Ludwig van Beethoven");
        assert!(has_beethoven, "Beethoven should be in the canon");
        let has_bach = top
            .iter()
            .any(|c| c.full_name.as_deref().unwrap_or("") == "Johann Sebastian Bach");
        assert!(has_bach, "Bach should be in the canon");
    }

    #[test]
    fn composers_by_era_bucket() {
        let provider = OpenOpusProvider::new();
        let baroque = provider.composers_by_era(Era::Baroque);
        // We always expect at least Bach + Handel + Vivaldi in the snapshot.
        let names: Vec<String> = baroque.iter().map(|c| c.name.clone()).collect();
        assert!(
            names.iter().any(|n| n.contains("Bach")),
            "baroque era should contain Bach: {names:?}"
        );
    }

    #[test]
    fn era_label_baroque() {
        assert_eq!(
            era_for_epoch_label(Some("Baroque"), Some(1685)),
            Era::Baroque
        );
    }

    #[test]
    fn era_label_late_romantic() {
        assert_eq!(
            era_for_epoch_label(Some("Late Romantic"), Some(1860)),
            Era::LateRomantic
        );
    }

    #[test]
    fn era_label_falls_back_to_year() {
        assert_eq!(era_for_epoch_label(None, Some(1685)), Era::Baroque);
        assert_eq!(era_for_epoch_label(None, Some(1985)), Era::Contemporary);
        assert_eq!(era_for_epoch_label(None, None), Era::Unknown);
    }

    #[test]
    fn genre_mapping() {
        assert_eq!(genre_for_oo_label(Some("Keyboard")), Some(Genre::SoloInstrumental));
        assert_eq!(genre_for_oo_label(Some("Orchestral")), Some(Genre::Orchestral));
        assert_eq!(genre_for_oo_label(Some("Stage")), Some(Genre::Opera));
        assert_eq!(genre_for_oo_label(None), None);
    }

    #[test]
    fn lookup_by_mbid() {
        let provider = OpenOpusProvider::new();
        // Bach's canonical MBID — same one the snapshot script resolves.
        let bach = provider.lookup_composer_by_mbid("24f1766e-9635-4d58-a4d4-9413f9f98a4c");
        assert!(bach.is_some(), "Bach should resolve via MBID lookup");
        let bach = bach.expect("checked above");
        assert!(bach.full_name.as_deref().unwrap_or("").contains("Bach"));
        assert_eq!(bach.epoch.as_deref(), Some("Baroque"));
    }

    #[test]
    fn works_for_composer_returns_some() {
        let provider = OpenOpusProvider::new();
        // Beethoven MBID
        let works = provider.works_for_composer("1f9df192-a621-4f54-8850-2c5373b7eac9");
        assert!(!works.is_empty(), "Beethoven should have works in the snapshot");
        // At least one popular work must be present (Symphony 9 or Pathétique).
        assert!(works.iter().any(|w| w.popular));
    }
}
